### ISSUE TITLE
1.2.2 vifm mount problem

### ISSUE THREAD

**Issue by amigthea** [andrew-grechkin/fuse3-p7zip#13]
as per title, after the update I cannot mount anymore in vifm, it gives me the error `Cannot open file.zip`

**Comment by andrew-grechkin** [comment]
the issue is not informative enough and thus is not actionable
I can successfully mount any archive on a new release

please provide more details to reproduce

**Comment by amigthea** [comment]
there is something wrong with my configuration, I was not able to reproduce it on a clean install, thank you for the feedback

**Comment by amigthea** [comment]
I think I nailed it down; the problem seems to appear when the command is wrapped in `su -c`

su -c "fuse3-p7zip file.zip /mnt/fuse" john

I tried it outside vifm, can you reproduce this?

**Comment by andrew-grechkin** [comment]
nope, not reproduced:

```bash
$ mkdir -p /tmp/zip/test
mkdir: created directory '/tmp/zip'
mkdir: created directory '/tmp/zip/test'

$ cd /tmp/zip

$ echo 12345 > test/file

$ zip -r archive.zip test
  adding: test/ (stored 0%)
  adding: test/file (stored 0%)

$ unzip -l archive.zip
Archive:  archive.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-11-11 20:13   test/
        6  2024-11-11 20:13   test/file
---------                     -------
        6                     2 files

$ su -c "fuse3-p7zip archive.zip /tmp/mnt" agrechkin
Password:

$ ls -la /tmp/mnt
total 8
drwxr-x---  1 agrechkin agrechkin 312 Nov 11 20:13 .
drwxrwxrwt 23 root      root      920 Nov 11 20:16 ..
drwxrwxr-x  1 agrechkin agrechkin   0 Nov 11 20:13 test
```

you need to check that user has permissions to the archive

**Comment by amigthea** [comment]
thank you for your time, I indeed checked the permissions, I think the problem shows up when using the -o `allow_other` argument.

in your example
`su -c "fuse3-p7zip -o allow_other archive.zip /tmp/mnt" agrechkin`

and then trying to navigate the mount with another user

**Comment by andrew-grechkin** [comment]
works for me with -o allow_other as well

**Comment by andrew-grechkin** [comment]
what was the point of not explaining this from the very beginning?

**Comment by amigthea** [comment]
> what was the point of not explaining this from the very beginning?
> 
> what are permissions and owner of the file.zip?

I'm sorry about that, I should've gathered and format a better issue from the beginning

the file.zip is owned by $USER, john

**Comment by andrew-grechkin** [comment]
I have reproduced the issue, indeed root has no access if mounted by some other user

**Comment by amigthea** [comment]
I'm getting a strange error when using `allow_root`

`su -c "fuse3-p7zip -o allow_root file.zip /mnt/fuse" john`

```
Critical error:
  fuse_parse_cmdline
```

**Comment by andrew-grechkin** [comment]
> I'm getting a strange error
add all `-o` after file and mountpoint

**Comment by amigthea** [comment]
as I originally used, thanks for the help

**Comment by andrew-grechkin** [comment]
the issue with `-o allow_others` is fixed - your initial setup should work properly
