### ISSUE TITLE
Mount an directory containing many types of compressed archives transparently into another directory

### ISSUE THREAD

**Issue by jkaberg** [andrew-grechkin/fuse3-p7zip#3]
Hi @andrew-grechkin, many thanks for creating this.

I was wondering if you have any thoughts on into supporting nested directories with compressed archives (more or less what rar2fs does)?

Eg  (just an example of what could be)
```
ls directory/
notcompressed.txt 1.rar 2.rar subdir/3.rar subdir/tool.bin subdir/nested/4.rar 
fuse3-p7zip directory/ output/
ls output/
notcompressed.txt 1_content 2_content subdir/3_content subdir/tool.bin subdir/nested/4_content
```

So more or less transparently send not compressed files through, and "unpack" compressed files in real time as a folder/file structure in the (output) mount directory

Utilizing p7zip for this would support a wide range of files instead of just rar files like rar2fs does.

**Comment by andrew-grechkin** [comment]
After some consideration and thinking about it I see that this should be done by external tool (script).
Feeding a directory with archives should just walk through all of them and mount them one by one separately. No need to change existing tool to incorporate this behavior - this would contradict with the unix philosophy.
